language: python
python:
  - 3.6
  - 3.5
  - 3.7
env:
  global:
    TORTOISE_TEST_MODULES=tortoise.tests.testmodels
env:
  - TORTOISE_TEST_DB="sqlite:///tmp/test-{}.sqlite"
  - TORTOISE_TEST_DB="postgres://postgres:@127.0.0.1:5432/test_{}"
  - TORTOISE_TEST_DB="mysql://root:@127.0.0.1:3306/test_{}"
matrix:
  include:
  - python: pypy3.5
    env: TORTOISE_TEST_DB="sqlite:///tmp/test-{}.sqlite"
    install: pip install -r requirements-pypy.txt
    script: green
  - python: pypy3.5
    env: TORTOISE_TEST_DB="mysql://root:@127.0.0.1:3306/test_{}"
    install: pip install -r requirements-pypy.txt
    script: green
  - python: 3.6
    env: TEST_RUNNER=py.test
    install: pip install -r requirements-dev.txt
    script: py.test
  - python: 3.6
    env: TEST_RUNNER=nose2
    install: pip install -r requirements-dev.txt
    script: "nose2 --plugin tortoise.contrib.test.nose2 --db-module tortoise.tests.testmodels --db-url sqlite://:memory:"
dist: xenial
services:
  - postgresql
  - mysql
cache: pip
install:
  - pip install -r requirements-dev.txt
script:
  - make ci
after_success:
  - coveralls
